directories:
  output: release
  buildResources: build
appId: com.yourname.golfballthree
productName: GolfBallViewer
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
asar: true
win:
  target: nsis
  icon: build/icon.ico
electronVersion: 39.0.0
